name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/821220798323/locations/global/workloadIdentityPools/knaks-cf363/providers/knaks-provider'
          service_account: 'knaks-service-account@knaks-cf363.iam.gserviceaccount.com'
          id_token_audience: 'https://knaks.app'

      - name: Deploy to Google Cloud
        run: |
          echo "Deployment complete"
